config/routes.rb
Rails.application.routes.draw do

  resources :contact_forms

  resources :area_of_expertises

  resources :db_members
  
  resources :locations 
  
  get 'password_resets/update'

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :sessions
  
  get "login"  => "sessions#new", :as => "login"

  namespace :admin do
    root to: "home#index"
  end

  get 'activities/index'

  get "aboutus"  => "aboutus#index", :as => "aboutus"
  get "NationalConvention"  => "national_convention#index", :as => "NationalConvention"
  get "resources"  => "resources#index", :as => "resources"
  get "contactus"  => "contactus#index", :as => "contactus"
  get "activities"  => "activities#index", :as => "activities"
  get "members" => "members#index", :as => "members"
  get "home"  => "home#index", :as => "home"
 
  root to: "home#index"

end

app/models/area_of_expertise.rb
class AreaOfExpertise < ActiveRecord::Base
end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
end

app/models/db_member.rb
class DbMember < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'bcrypt'
  attr_accessor :password
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true
  validates :password, :confirmation => true #password_confirmation attr
  before_save :encrypt_password
  after_save :clear_password
  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
    end
  end
  def clear_password
    self.password = nil
  end
  
  def new_remember_token
    @token = SecureRandom.urlsafe_base64
    return @token
    
  end
  
  def encrypt_token(token)
    return Digest::SHA1.hexdigest(token.to_s)
  end  
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  
 # redirect_to sessions_path
  
  def pagination_page
    params[:page] ||= 1
    params[:page].to_i
  end

  def pagination_rows
    params[:rows] ||= 10
    params[:rows].to_i
  end
  
  def store_location
    session[:return_to] = request.env["HTTP_REFERER"] 
    
  end

  def redirect_back_or(default, hsh = {})
     redirect_to(session[:return_to] || default, hsh )
     clear_return_to
  end

  def clear_return_to
   session[:return_to] = nil
  end
  
end

app/controllers/db_members_controller.rb
class DbMembersController < ApplicationController
  before_action :set_db_member, only: [:show, :edit, :update, :destroy]

  # GET /db_members
  # GET /db_members.json
  def index
    require_user()
    @db_members = DbMember.all
  end

  # GET /db_members/1
  # GET /db_members/1.json
  def show
    require_user()
  end

  # GET /db_members/new
  def new
    require_user()
    @db_member = DbMember.new
  end

  # GET /db_members/1/edit
  def edit
    require_user()
  end

  # POST /db_members
  # POST /db_members.json
  def create
    require_user()
    @db_member = DbMember.new(db_member_params)

    respond_to do |format|
      if @db_member.save
        format.html { redirect_to @db_member, notice: 'Db member was successfully created.' }
        format.json { render :show, status: :created, location: @db_member }
      else
        format.html { render :new }
        format.json { render json: @db_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /db_members/1
  # PATCH/PUT /db_members/1.json
  def update
    require_user()
    respond_to do |format|
      if @db_member.update(db_member_params)
        format.html { redirect_to @db_member, notice: 'Db member was successfully updated.' }
        format.json { render :show, status: :ok, location: @db_member }
      else
        format.html { render :edit }
        format.json { render json: @db_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /db_members/1
  # DELETE /db_members/1.json
  def destroy
    require_user()
    @db_member.destroy
    respond_to do |format|
      format.html { redirect_to db_members_url, notice: 'Db member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_db_member
      @db_member = DbMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def db_member_params
      params.require(:db_member).permit(:MembershipId, :MembershipType, :Certified, :Prefix, :FirstName, :MiddleName, :LastName, :Title, :ShortSummary, :FullSammary, :Address, :City, :Pin, :MobilePhone, :LandLine, :EmailPrimary, :Email, :Secondary, :WebsitePrimary, :WebsiteSecondary, :DisplayOrder, :active, :IsAdmin)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :encrypted_password, :password, :password_confirmation, :salt, :remember_token)
    end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/helpers/db_members_helper.rb
module DbMembersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/db_members/_form.html.erb
<%= form_for(@db_member) do |f| %>
  <% if @db_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@db_member.errors.count, "error") %> prohibited this db_member from being saved:</h2>

      <ul>
      <% @db_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :MembershipId %><br>
    <%= f.text_field :MembershipId %>
  </div>
  <div class="field">
    <%= f.label :MembershipType %><br>
    <%= f.text_field :MembershipType %>
  </div>
  <div class="field">
    <%= f.label :Certified %><br>
    <%= f.check_box :Certified %>
  </div>
  <div class="field">
    <%= f.label :Prefix %><br>
    <%= f.text_field :Prefix %>
  </div>
  <div class="field">
    <%= f.label :FirstName %><br>
    <%= f.text_field :FirstName %>
  </div>
  <div class="field">
    <%= f.label :MiddleName %><br>
    <%= f.text_field :MiddleName %>
  </div>
  <div class="field">
    <%= f.label :LastName %><br>
    <%= f.text_field :LastName %>
  </div>
  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :ShortSummary %><br>
    <%= f.text_field :ShortSummary %>
  </div>
  <div class="field">
    <%= f.label :FullSammary %><br>
    <%= f.text_field :FullSammary %>
  </div>
  <div class="field">
    <%= f.label :Address %><br>
    <%= f.text_field :Address %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :Pin %><br>
    <%= f.text_field :Pin %>
  </div>
  <div class="field">
    <%= f.label :MobilePhone %><br>
    <%= f.text_field :MobilePhone %>
  </div>
  <div class="field">
    <%= f.label :LandLine %><br>
    <%= f.text_field :LandLine %>
  </div>
  <div class="field">
    <%= f.label :EmailPrimary %><br>
    <%= f.text_field :EmailPrimary %>
  </div>
  <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_field :Email %>
  </div>
  <div class="field">
    <%= f.label :Secondary %><br>
    <%= f.text_field :Secondary %>
  </div>
  <div class="field">
    <%= f.label :WebsitePrimary %><br>
    <%= f.text_field :WebsitePrimary %>
  </div>
  <div class="field">
    <%= f.label :WebsiteSecondary %><br>
    <%= f.text_field :WebsiteSecondary %>
  </div>
  <div class="field">
    <%= f.label :DisplayOrder %><br>
    <%= f.text_field :DisplayOrder %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :IsAdmin %><br>
    <%= f.check_box :IsAdmin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/db_members/edit.html.erb
<h1>Editing db_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @db_member %> |
<%= link_to 'Back', db_members_path %>

app/views/db_members/index.html.erb
<h1>Listing db_members</h1>

<table>
  <thead>
    <tr>
      <th>Membershipid</th>
      <th>Membershiptype</th>
      <th>Certified</th>
      <th>Prefix</th>
      <th>Firstname</th>
      <th>Middlename</th>
      <th>Lastname</th>
      <th>Title</th>
      <th>Shortsummary</th>
      <th>Fullsammary</th>
      <th>Address</th>
      <th>City</th>
      <th>Pin</th>
      <th>Mobilephone</th>
      <th>Landline</th>
      <th>Emailprimary</th>
      <th>Email</th>
      <th>Secondary</th>
      <th>Websiteprimary</th>
      <th>Websitesecondary</th>
      <th>Displayorder</th>
      <th>Active</th>
      <th>Isadmin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @db_members.each do |db_member| %>
      <tr>
        <td><%= db_member.MembershipId %></td>
        <td><%= db_member.MembershipType %></td>
        <td><%= db_member.Certified %></td>
        <td><%= db_member.Prefix %></td>
        <td><%= db_member.FirstName %></td>
        <td><%= db_member.MiddleName %></td>
        <td><%= db_member.LastName %></td>
        <td><%= db_member.Title %></td>
        <td><%= db_member.ShortSummary %></td>
        <td><%= db_member.FullSammary %></td>
        <td><%= db_member.Address %></td>
        <td><%= db_member.City %></td>
        <td><%= db_member.Pin %></td>
        <td><%= db_member.MobilePhone %></td>
        <td><%= db_member.LandLine %></td>
        <td><%= db_member.EmailPrimary %></td>
        <td><%= db_member.Email %></td>
        <td><%= db_member.Secondary %></td>
        <td><%= db_member.WebsitePrimary %></td>
        <td><%= db_member.WebsiteSecondary %></td>
        <td><%= db_member.DisplayOrder %></td>
        <td><%= db_member.active %></td>
        <td><%= db_member.IsAdmin %></td>
        <td><%= link_to 'Show', db_member %></td>
        <td><%= link_to 'Edit', edit_db_member_path(db_member) %></td>
        <td><%= link_to 'Destroy', db_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Db member', new_db_member_path %>

app/views/db_members/new.html.erb
<h1>New db_member</h1>

<%= render 'form' %>

<%= link_to 'Back', db_members_path %>

app/views/db_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Membershipid:</strong>
  <%= @db_member.MembershipId %>
</p>

<p>
  <strong>Membershiptype:</strong>
  <%= @db_member.MembershipType %>
</p>

<p>
  <strong>Certified:</strong>
  <%= @db_member.Certified %>
</p>

<p>
  <strong>Prefix:</strong>
  <%= @db_member.Prefix %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @db_member.FirstName %>
</p>

<p>
  <strong>Middlename:</strong>
  <%= @db_member.MiddleName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @db_member.LastName %>
</p>

<p>
  <strong>Title:</strong>
  <%= @db_member.Title %>
</p>

<p>
  <strong>Shortsummary:</strong>
  <%= @db_member.ShortSummary %>
</p>

<p>
  <strong>Fullsammary:</strong>
  <%= @db_member.FullSammary %>
</p>

<p>
  <strong>Address:</strong>
  <%= @db_member.Address %>
</p>

<p>
  <strong>City:</strong>
  <%= @db_member.City %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @db_member.Pin %>
</p>

<p>
  <strong>Mobilephone:</strong>
  <%= @db_member.MobilePhone %>
</p>

<p>
  <strong>Landline:</strong>
  <%= @db_member.LandLine %>
</p>

<p>
  <strong>Emailprimary:</strong>
  <%= @db_member.EmailPrimary %>
</p>

<p>
  <strong>Email:</strong>
  <%= @db_member.Email %>
</p>

<p>
  <strong>Secondary:</strong>
  <%= @db_member.Secondary %>
</p>

<p>
  <strong>Websiteprimary:</strong>
  <%= @db_member.WebsitePrimary %>
</p>

<p>
  <strong>Websitesecondary:</strong>
  <%= @db_member.WebsiteSecondary %>
</p>

<p>
  <strong>Displayorder:</strong>
  <%= @db_member.DisplayOrder %>
</p>

<p>
  <strong>Active:</strong>
  <%= @db_member.active %>
</p>

<p>
  <strong>Isadmin:</strong>
  <%= @db_member.IsAdmin %>
</p>

<%= link_to 'Edit', edit_db_member_path(@db_member) %> |
<%= link_to 'Back', db_members_path %>